spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8&allowPublicKeyRetrieval=true&allowMultiQueries=true
    password: nimeishao11@@
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.yx: info
  file:
    path: log/blog-pro.log

server:
  port: 8081



